### ISSUE TITLE
supporting more than 4 dimension?

### ISSUE THREAD

**Issue by amirshamaei** [cabeen/niftijio#7]
Hi,
thank you very much for such a great library.
I want to use the dimension 5, 6, and 7. I understand it is not possible with this lib.
could I fork your repo and develop?
best,

**Comment by cabeen** [comment]
Hi Amir,

Thanks, yes, please do feel free to add these features if you find them useful!

Cheers,
Ryan

**Comment by amirshamaei** [comment]
Sorry for the late response. I am using your library for  Magnetic resonance spectroscopy data. I added new features such as N-Dimension support, slice and time selection, and Random access. Currently, I am testing it and dealing with bugs.
If it works, then I need to figure out why it's working :))) 
Best,

**Comment by amirshamaei** [comment]
hi @cabeen ; I hope you are well.
I forked and pushed my edited-version.  I tried to keep the FourdimensionalArray class, but having two data classes was a source of bugs. 
people, who may be interested, can find it here:
https://github.com/amirshamaei/niftijio
Kind regards,
